name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest


    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Login to Amazon ECR
      id: login-ecr
<<<<<<< HEAD
      uses: aws-actions/amazon-ecr-login@v1
=======
      uses: aws-actions/amazon-ecr-login@v2
>>>>>>> 65e6f5b0be53db9ae1c511d1a246271c433024f2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: takeeasybank
        IMAGE_TAG: ${{ github.sha }}
      run: |
<<<<<<< HEAD
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
=======
        docker build -t $ECR_REGISTRY/$ECR_REPOSITO
>>>>>>> 65e6f5b0be53db9ae1c511d1a246271c433024f2
